import createTypes from 'redux-create-action-types';

export default createTypes(
  'ACTIVITIES_ADD',
  'ACTIVITIES_INITIALIZE',
  'ACTIVITIES_REMOVE',
  'ACTIVITIES_REMOVE_ALL',
  'ACTIVITIES_SET_LAST_SEEN',
  'ACTIVITIES_SET_STATUS',
  'ACTIVITIES_UPDATE',
  'ACTIVITIES_UPDATE_ERROR',
  'ACTIVITIES_UPDATE_SUCCESS',
);
