import createTypes from 'redux-create-action-types';

export default createTypes(
  'TOKEN_BALANCE_UPDATE',
  'TOKEN_BALANCE_UPDATE_ERROR',
  'TOKEN_BALANCE_UPDATE_SUCCESS',
  'TOKEN_DEPLOY',
  'TOKEN_DEPLOY_ERROR',
  'TOKEN_DEPLOY_SUCCESS',
  'TOKEN_RESET',
  'TOKEN_TRANSFER',
  'TOKEN_TRANSFER_ERROR',
  'TOKEN_TRANSFER_SUCCESS',
  'TOKEN_UPDATE',
  'TOKEN_UPDATE_ERROR',
  'TOKEN_UPDATE_SUCCESS',
);
