name: Auto Assign Issues to Projects

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    - name: Assign all NEW issues to project 50
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/CirclesUBI/projects/50'

    - name: Assign issues with `bug` label to project 23
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'bug :boom:')
      with:
        project: 'https://github.com/orgs/CirclesUBI/projects/23'
        column_name: 'Labeled'
